config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users, only: [:new, :create, :show]
  resources :links
end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :user
  validates :url, :url => {:no_local => true, :message => "Something is up with that URL. Visit it in your browse and then copy that exact link!"}
  validates :title, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :links
  has_secure_password
  validates_confirmation_of :password
  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def index
    @link = Link.new
    @links = current_user.links
  end

  def create
    @link = current_user.links.create(link_params)
    if @link.save
      flash[:success] = "New Link Added!"
      redirect_to links_path
    else
      flash[:info] = "#{@link.errors.full_messages.join(', ')}"
      redirect_to links_path
    end
  end

  def update
    @link = Link.find(params[:id])

    if params[:read]
      @link.update(read: params[:read])
      head :no_content
    else
      attribute = params[:link].keys[0]
      @link.update(attribute => params[:link][attribute])
      head :no_content
    end
  end

  private

  def link_params
    params.require(:link).permit(:url, :title, :read)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    session[:return_to] ||= request.referer
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      session[:user_id]  = user.id
      flash[:info] = "Hey #{user.email}, welcome to THOUGHTBOX"
      redirect_to links_path
    else
        flash.now[:alert] = "Sorry, friend.  Something went wrong :(... Please try again."
        render :new
    end
  end

  def destroy
    flash[:bye] = "Sad to see you go #{current_user.email}. Come back again soon. 👋"
    session.clear
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
    session[:user_id] = @user.id
    flash[:info] = "Hey #{@user.email}, welcome to THOUGHTBOX"
    redirect_to root_path
    else
      flash.now[:alert] = "Whoops! #{@user.errors.full_messages.join(', ')}"
      render :new
    end
  end

  def show
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="container">
  <h1>Welcome to Thoughbox</h1>

  <%= link_to 'Sign Up', new_user_path %>
  <%= link_to 'Sign In', login_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Thoughtbox</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1"></head>
  <body>
  <% flash.each do |type, message| %>
    <%= content_tag :div, sanitize(message), class: "alert alert_#{type} admin-flash" %>
  <% end %>

  <%= yield %>

  </body>
</html>

app/views/links/index.html.erb
<nav role="navigation" class="navbar navbar-default custom-navbar">
  <div class="nav-container">
    <%= link_to "logout", logout_path, method: :delete %>
  </div>
</nav>
<div class="text-center">
<div class="container">
  <h3>NEW LINK</h3>
  <%= form_for(@link) do |f| %>
    <%= f.label :url, class:"sr-only"  %>
    <%= f.text_field :url, placeholder: "url", class:"form-control text-input", required:true %><br>
    <%= f.label :title, class:"sr-only"  %>
    <%= f.text_field :title, placeholder: "title", class:"form-control text-input", required:true %><br>
    <%= f.submit "submit link", class:"btn btn-success" %>
  <% end %>
</div><br><hr>
<h1>SEARCH</h1>
  <div class="searchLink container" id="searchLink">
      <form class="form-inline searchLinkForm">
        <div class="form-group">
          <input type="text_field" size="80" id="search" placeholder="Search" class="form-control" required>
        </div>
        <div class="form-group">
          <button type="submit" class="btn btn-info btn-md"  value="clear" id="clear">Clear</button>
        </div>
      </form>
      <br>
      <button type="button" class="btn btn-success filterRead">Filter Only Read</button>
      <button type="button" class="btn btn-danger filterUnread">Filter Only Unread</button>
      <button type="button" class="btn btn-info showAll">Show All</button><br><br>
      <button type="button" class="btn btn-info sort asc">Sort A-Z</button>
      <button type="button" class="btn btn-info sort desc">Sort Z-A</button>
  </div><hr>
<div class="container links">
  <h1>My Links</h1>
  <table class="table links-table">
    <th>Title</th>
    <th>URL</th>
    <th>Mark as Read?</th>
    <tbody class="table-striped table-center">
      <% @links.each do |link| %>
      <tr class='link' id="link-<%= link.id %>">
        <%= form_for(link) do |f| %>
          <%= f.label :title, class:"sr-only"  %>
          <td class='title'><%= f.text_field :title, class:"form-control text-input edit title", readonly:true, :data => {:id => link.id }%></td>
          <%= f.label :url, class:"sr-only"  %>
          <td class='url'><%= f.text_field :url, class:"form-control text-input edit url", readonly:true, :data => {:id => link.id } %></td>

          <% if link.read %>
            <td class='read'><button class="btn btn-success read" data-id="<%= link.id %>" data-read='false'>mark unread</button></td>
          <% else %>
            <td class='unread'><button class="btn btn-danger read" data-id="<%= link.id %>" data-read='true'>mark read</button></td>
          <% end %>
        <% end %>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<hr>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="row text-center">
    <div class="col-xs-3">
    </div>
    <div class="col-xs-6">
      <h1><small>sign up 🎉</small></h1>
    </div>
    <div class="col-xs-3">
    </div>
  </div>

  <br>
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3">
      <div class="form-group text-center form-div">
        <%= form_for(@user) do |f| %>
          <%= f.label :email, class:"sr-only"  %>
          <%= f.email_field :email, placeholder: "email", class:"form-control text-input" %><br>
          <%= f.label :password, class:"sr-only"  %>
          <%= f.password_field :password, placeholder: "password", class:"form-control text-input" %><br>
          <%= f.password_field :password_confirmation, placeholder: "password confirmation", class:"form-control text-input" %><br>
          <%= f.submit "signup", class:"btn btn-success" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>